using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace ERPCore2.Migrations
{
    /// <inheritdoc />
    public partial class AddSubAccountFields : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<bool>(
                name: "AutoCreateCustomerSubAccount",
                table: "SystemParameters",
                type: "bit",
                nullable: false,
                defaultValue: false);

            migrationBuilder.AddColumn<bool>(
                name: "AutoCreateProductSubAccount",
                table: "SystemParameters",
                type: "bit",
                nullable: false,
                defaultValue: false);

            migrationBuilder.AddColumn<bool>(
                name: "AutoCreateSupplierSubAccount",
                table: "SystemParameters",
                type: "bit",
                nullable: false,
                defaultValue: false);

            migrationBuilder.AddColumn<string>(
                name: "CustomerSubAccountParentCode",
                table: "SystemParameters",
                type: "nvarchar(20)",
                maxLength: 20,
                nullable: false,
                defaultValue: "");

            migrationBuilder.AddColumn<string>(
                name: "ProductSubAccountParentCode",
                table: "SystemParameters",
                type: "nvarchar(20)",
                maxLength: 20,
                nullable: false,
                defaultValue: "");

            migrationBuilder.AddColumn<string>(
                name: "SupplierSubAccountParentCode",
                table: "SystemParameters",
                type: "nvarchar(20)",
                maxLength: 20,
                nullable: false,
                defaultValue: "");

            migrationBuilder.AddColumn<bool>(
                name: "IsAutoGenerated",
                table: "AccountItems",
                type: "bit",
                nullable: false,
                defaultValue: false);

            migrationBuilder.AddColumn<int>(
                name: "LinkedCustomerId",
                table: "AccountItems",
                type: "int",
                nullable: true);

            migrationBuilder.AddColumn<int>(
                name: "LinkedProductId",
                table: "AccountItems",
                type: "int",
                nullable: true);

            migrationBuilder.AddColumn<int>(
                name: "LinkedSupplierId",
                table: "AccountItems",
                type: "int",
                nullable: true);

            migrationBuilder.CreateIndex(
                name: "IX_AccountItems_LinkedCustomerId",
                table: "AccountItems",
                column: "LinkedCustomerId",
                filter: "[LinkedCustomerId] IS NOT NULL");

            migrationBuilder.CreateIndex(
                name: "IX_AccountItems_LinkedProductId",
                table: "AccountItems",
                column: "LinkedProductId",
                filter: "[LinkedProductId] IS NOT NULL");

            migrationBuilder.CreateIndex(
                name: "IX_AccountItems_LinkedSupplierId",
                table: "AccountItems",
                column: "LinkedSupplierId",
                filter: "[LinkedSupplierId] IS NOT NULL");

            migrationBuilder.AddForeignKey(
                name: "FK_AccountItems_Customers_LinkedCustomerId",
                table: "AccountItems",
                column: "LinkedCustomerId",
                principalTable: "Customers",
                principalColumn: "Id",
                onDelete: ReferentialAction.SetNull);

            migrationBuilder.AddForeignKey(
                name: "FK_AccountItems_Products_LinkedProductId",
                table: "AccountItems",
                column: "LinkedProductId",
                principalTable: "Products",
                principalColumn: "Id",
                onDelete: ReferentialAction.SetNull);

            migrationBuilder.AddForeignKey(
                name: "FK_AccountItems_Suppliers_LinkedSupplierId",
                table: "AccountItems",
                column: "LinkedSupplierId",
                principalTable: "Suppliers",
                principalColumn: "Id",
                onDelete: ReferentialAction.SetNull);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_AccountItems_Customers_LinkedCustomerId",
                table: "AccountItems");

            migrationBuilder.DropForeignKey(
                name: "FK_AccountItems_Products_LinkedProductId",
                table: "AccountItems");

            migrationBuilder.DropForeignKey(
                name: "FK_AccountItems_Suppliers_LinkedSupplierId",
                table: "AccountItems");

            migrationBuilder.DropIndex(
                name: "IX_AccountItems_LinkedCustomerId",
                table: "AccountItems");

            migrationBuilder.DropIndex(
                name: "IX_AccountItems_LinkedProductId",
                table: "AccountItems");

            migrationBuilder.DropIndex(
                name: "IX_AccountItems_LinkedSupplierId",
                table: "AccountItems");

            migrationBuilder.DropColumn(
                name: "AutoCreateCustomerSubAccount",
                table: "SystemParameters");

            migrationBuilder.DropColumn(
                name: "AutoCreateProductSubAccount",
                table: "SystemParameters");

            migrationBuilder.DropColumn(
                name: "AutoCreateSupplierSubAccount",
                table: "SystemParameters");

            migrationBuilder.DropColumn(
                name: "CustomerSubAccountParentCode",
                table: "SystemParameters");

            migrationBuilder.DropColumn(
                name: "ProductSubAccountParentCode",
                table: "SystemParameters");

            migrationBuilder.DropColumn(
                name: "SupplierSubAccountParentCode",
                table: "SystemParameters");

            migrationBuilder.DropColumn(
                name: "IsAutoGenerated",
                table: "AccountItems");

            migrationBuilder.DropColumn(
                name: "LinkedCustomerId",
                table: "AccountItems");

            migrationBuilder.DropColumn(
                name: "LinkedProductId",
                table: "AccountItems");

            migrationBuilder.DropColumn(
                name: "LinkedSupplierId",
                table: "AccountItems");
        }
    }
}
