using ERPCore2.Data.Context;
using ERPCore2.Models.Charts;
using ERPCore2.Models.Enums;
using Microsoft.EntityFrameworkCore;

namespace ERPCore2.Services.FinancialManagement;

public class FinancialChartService : IFinancialChartService
{
    private readonly IDbContextFactory<AppDbContext> _factory;

    public FinancialChartService(IDbContextFactory<AppDbContext> factory)
    {
        _factory = factory;
    }

    /// <summary>依沖款類型分布（應收/應付）</summary>
    public async Task<List<ChartDataItem>> GetSetoffByTypeAsync()
    {
        using var context = await _factory.CreateDbContextAsync();

        var rows = await context.SetoffDocuments
            .Where(x => x.Status != EntityStatus.Deleted)
            .Select(x => new { x.SetoffType })
            .ToListAsync();

        return rows
            .GroupBy(x => x.SetoffType)
            .Select(g => new ChartDataItem
            {
                Label = g.Key == SetoffType.AccountsReceivable ? "應收帳款沖款" : "應付帳款沖款",
                Value = g.Count()
            })
            .OrderByDescending(x => x.Value)
            .ToList();
    }

    /// <summary>每月沖款金額趨勢（近 N 個月）</summary>
    public async Task<List<ChartDataItem>> GetMonthlySetoffTrendAsync(int months = 12)
    {
        using var context = await _factory.CreateDbContextAsync();

        var now = DateTime.Now;
        var startDate = new DateTime(now.AddMonths(-(months - 1)).Year, now.AddMonths(-(months - 1)).Month, 1);

        var rows = await context.SetoffDocuments
            .Where(x => x.Status != EntityStatus.Deleted && x.SetoffDate >= startDate)
            .Select(x => new { x.SetoffDate, x.CurrentSetoffAmount })
            .ToListAsync();

        var grouped = rows
            .GroupBy(x => new { x.SetoffDate.Year, x.SetoffDate.Month })
            .ToDictionary(g => (g.Key.Year, g.Key.Month), g => g.Sum(x => x.CurrentSetoffAmount));

        var result = new List<ChartDataItem>();
        for (int i = months - 1; i >= 0; i--)
        {
            var date = now.AddMonths(-i);
            grouped.TryGetValue((date.Year, date.Month), out var total);
            result.Add(new ChartDataItem { Label = date.ToString("yyyy/MM"), Value = total });
        }
        return result;
    }

    /// <summary>依關聯方沖款金額排行 Top N</summary>
    public async Task<List<ChartDataItem>> GetTopSetoffByAmountAsync(int top = 10)
    {
        using var context = await _factory.CreateDbContextAsync();

        var rows = await context.SetoffDocuments
            .Where(x => x.Status != EntityStatus.Deleted)
            .Select(x => new { x.RelatedPartyId, x.RelatedPartyType, x.CurrentSetoffAmount })
            .ToListAsync();

        // 取得客戶名稱
        var customerIds = rows.Where(x => x.RelatedPartyType == "Customer").Select(x => x.RelatedPartyId).Distinct().ToList();
        var supplierIds = rows.Where(x => x.RelatedPartyType == "Supplier").Select(x => x.RelatedPartyId).Distinct().ToList();

        var customers = await context.Customers
            .Where(c => customerIds.Contains(c.Id))
            .Select(c => new { c.Id, Name = c.CompanyName ?? c.Code ?? $"ID:{c.Id}" })
            .ToListAsync();
        var suppliers = await context.Suppliers
            .Where(s => supplierIds.Contains(s.Id))
            .Select(s => new { s.Id, Name = s.CompanyName ?? s.Code ?? $"ID:{s.Id}" })
            .ToListAsync();

        var customerMap = customers.ToDictionary(x => x.Id, x => x.Name);
        var supplierMap = suppliers.ToDictionary(x => x.Id, x => x.Name);

        return rows
            .GroupBy(x => new { x.RelatedPartyId, x.RelatedPartyType })
            .Select(g =>
            {
                var name = g.Key.RelatedPartyType == "Customer"
                    ? customerMap.GetValueOrDefault(g.Key.RelatedPartyId, $"客戶ID:{g.Key.RelatedPartyId}")
                    : supplierMap.GetValueOrDefault(g.Key.RelatedPartyId, $"廠商ID:{g.Key.RelatedPartyId}");
                return new ChartDataItem { Label = name, Value = g.Sum(x => x.CurrentSetoffAmount) };
            })
            .OrderByDescending(x => x.Value)
            .Take(top)
            .ToList();
    }

    /// <summary>依傳票類型分布</summary>
    public async Task<List<ChartDataItem>> GetJournalByTypeAsync()
    {
        using var context = await _factory.CreateDbContextAsync();

        var rows = await context.JournalEntries
            .Where(x => x.Status != EntityStatus.Deleted)
            .Select(x => new { x.EntryType })
            .ToListAsync();

        var typeLabels = new Dictionary<JournalEntryType, string>
        {
            [JournalEntryType.AutoGenerated]  = "自動產生",
            [JournalEntryType.Manual]         = "手動輸入",
            [JournalEntryType.Adjusting]      = "調整分錄",
            [JournalEntryType.Closing]        = "結帳分錄",
            [JournalEntryType.Reversing]      = "沖銷分錄",
            [JournalEntryType.OpeningBalance] = "期初餘額"
        };

        return rows
            .GroupBy(x => x.EntryType)
            .Select(g => new ChartDataItem
            {
                Label = typeLabels.GetValueOrDefault(g.Key, g.Key.ToString()),
                Value = g.Count()
            })
            .OrderByDescending(x => x.Value)
            .ToList();
    }

    /// <summary>每月傳票金額趨勢（已過帳傳票，近 N 個月）</summary>
    public async Task<List<ChartDataItem>> GetMonthlyJournalTrendAsync(int months = 12)
    {
        using var context = await _factory.CreateDbContextAsync();

        var now = DateTime.Now;
        var startDate = new DateTime(now.AddMonths(-(months - 1)).Year, now.AddMonths(-(months - 1)).Month, 1);

        var rows = await context.JournalEntries
            .Where(x => x.Status != EntityStatus.Deleted
                     && x.JournalEntryStatus == JournalEntryStatus.Posted
                     && x.EntryDate >= startDate)
            .Select(x => new { x.EntryDate, x.TotalDebitAmount })
            .ToListAsync();

        var grouped = rows
            .GroupBy(x => new { x.EntryDate.Year, x.EntryDate.Month })
            .ToDictionary(g => (g.Key.Year, g.Key.Month), g => g.Sum(x => x.TotalDebitAmount));

        var result = new List<ChartDataItem>();
        for (int i = months - 1; i >= 0; i--)
        {
            var date = now.AddMonths(-i);
            grouped.TryGetValue((date.Year, date.Month), out var total);
            result.Add(new ChartDataItem { Label = date.ToString("yyyy/MM"), Value = total });
        }
        return result;
    }

    /// <summary>依傳票狀態分布</summary>
    public async Task<List<ChartDataItem>> GetJournalByStatusAsync()
    {
        using var context = await _factory.CreateDbContextAsync();

        var rows = await context.JournalEntries
            .Where(x => x.Status != EntityStatus.Deleted)
            .Select(x => new { x.JournalEntryStatus })
            .ToListAsync();

        var statusLabels = new Dictionary<JournalEntryStatus, string>
        {
            [JournalEntryStatus.Draft]     = "草稿",
            [JournalEntryStatus.Posted]    = "已過帳",
            [JournalEntryStatus.Cancelled] = "已取消",
            [JournalEntryStatus.Reversed]  = "已沖銷"
        };

        return rows
            .GroupBy(x => x.JournalEntryStatus)
            .Select(g => new ChartDataItem
            {
                Label = statusLabels.GetValueOrDefault(g.Key, g.Key.ToString()),
                Value = g.Count()
            })
            .OrderByDescending(x => x.Value)
            .ToList();
    }

    /// <summary>取得財務管理統計摘要</summary>
    public async Task<FinancialChartSummary> GetSummaryAsync()
    {
        using var context = await _factory.CreateDbContextAsync();

        var now = DateTime.Now;
        var firstOfMonth = new DateTime(now.Year, now.Month, 1);

        var setoffThisMonth = await context.SetoffDocuments
            .Where(x => x.Status != EntityStatus.Deleted && x.SetoffDate >= firstOfMonth)
            .Select(x => new { x.SetoffType, x.CurrentSetoffAmount })
            .ToListAsync();

        var journalThisMonth = await context.JournalEntries
            .CountAsync(x => x.Status != EntityStatus.Deleted && x.EntryDate >= firstOfMonth);

        var draftJournals = await context.JournalEntries
            .CountAsync(x => x.Status != EntityStatus.Deleted && x.JournalEntryStatus == JournalEntryStatus.Draft);

        return new FinancialChartSummary
        {
            TotalSetoffDocumentsThisMonth = setoffThisMonth.Count,
            TotalARSetoffAmount           = setoffThisMonth.Where(x => x.SetoffType == SetoffType.AccountsReceivable).Sum(x => x.CurrentSetoffAmount),
            TotalAPSetoffAmount           = setoffThisMonth.Where(x => x.SetoffType == SetoffType.AccountsPayable).Sum(x => x.CurrentSetoffAmount),
            TotalJournalEntriesThisMonth  = journalThisMonth,
            DraftJournalEntries           = draftJournals
        };
    }

    // ===== Drill-down 明細查詢 =====

    /// <summary>依沖款類型 Drill-down</summary>
    public async Task<List<ChartDetailItem>> GetSetoffDetailsByTypeAsync(string typeLabel)
    {
        using var context = await _factory.CreateDbContextAsync();

        var setoffType = typeLabel == "應收帳款沖款" ? SetoffType.AccountsReceivable : SetoffType.AccountsPayable;

        var raw = await context.SetoffDocuments
            .Where(x => x.Status != EntityStatus.Deleted && x.SetoffType == setoffType)
            .OrderByDescending(x => x.SetoffDate)
            .Select(x => new { x.Id, x.Code, x.SetoffDate, x.CurrentSetoffAmount })
            .Take(30)
            .ToListAsync();

        return raw.Select(x => new ChartDetailItem
        {
            Id       = x.Id,
            Name     = x.SetoffDate.ToString("yyyy/MM/dd"),
            SubLabel = $"NT${x.CurrentSetoffAmount:N0}"
        }).ToList();
    }

    /// <summary>依關聯方沖款 Drill-down</summary>
    public async Task<List<ChartDetailItem>> GetSetoffDetailsByPartyAsync(string partyLabel)
    {
        using var context = await _factory.CreateDbContextAsync();

        // 先找出符合名稱的客戶/廠商 ID
        var customerIds = await context.Customers
            .Where(c => (c.CompanyName ?? c.Code ?? "") == partyLabel)
            .Select(c => c.Id).ToListAsync();
        var supplierIds = await context.Suppliers
            .Where(s => (s.CompanyName ?? s.Code ?? "") == partyLabel)
            .Select(s => s.Id).ToListAsync();

        var raw = await context.SetoffDocuments
            .Where(x => x.Status != EntityStatus.Deleted &&
                ((x.RelatedPartyType == "Customer" && customerIds.Contains(x.RelatedPartyId)) ||
                 (x.RelatedPartyType == "Supplier" && supplierIds.Contains(x.RelatedPartyId))))
            .OrderByDescending(x => x.SetoffDate)
            .Select(x => new { x.Id, x.Code, x.SetoffDate, x.CurrentSetoffAmount })
            .Take(30)
            .ToListAsync();

        return raw.Select(x => new ChartDetailItem
        {
            Id       = x.Id,
            Name     = x.SetoffDate.ToString("yyyy/MM/dd"),
            SubLabel = $"NT${x.CurrentSetoffAmount:N0}"
        }).ToList();
    }

    /// <summary>依傳票類型 Drill-down</summary>
    public async Task<List<ChartDetailItem>> GetJournalDetailsByTypeAsync(string typeLabel)
    {
        using var context = await _factory.CreateDbContextAsync();

        var typeMap = new Dictionary<string, JournalEntryType>
        {
            ["自動產生"] = JournalEntryType.AutoGenerated,
            ["手動輸入"] = JournalEntryType.Manual,
            ["調整分錄"] = JournalEntryType.Adjusting,
            ["結帳分錄"] = JournalEntryType.Closing,
            ["沖銷分錄"] = JournalEntryType.Reversing,
            ["期初餘額"] = JournalEntryType.OpeningBalance
        };

        if (!typeMap.TryGetValue(typeLabel, out var entryType))
            return new List<ChartDetailItem>();

        var raw = await context.JournalEntries
            .Where(x => x.Status != EntityStatus.Deleted && x.EntryType == entryType)
            .OrderByDescending(x => x.EntryDate)
            .Select(x => new { x.Id, x.Code, x.EntryDate, x.TotalDebitAmount })
            .Take(30)
            .ToListAsync();

        return raw.Select(x => new ChartDetailItem
        {
            Id       = x.Id,
            Name     = x.EntryDate.ToString("yyyy/MM/dd"),
            SubLabel = $"NT${x.TotalDebitAmount:N0}"
        }).ToList();
    }

    /// <summary>依傳票狀態 Drill-down</summary>
    public async Task<List<ChartDetailItem>> GetJournalDetailsByStatusAsync(string statusLabel)
    {
        using var context = await _factory.CreateDbContextAsync();

        var statusMap = new Dictionary<string, JournalEntryStatus>
        {
            ["草稿"]  = JournalEntryStatus.Draft,
            ["已過帳"] = JournalEntryStatus.Posted,
            ["已取消"] = JournalEntryStatus.Cancelled,
            ["已沖銷"] = JournalEntryStatus.Reversed
        };

        if (!statusMap.TryGetValue(statusLabel, out var status))
            return new List<ChartDetailItem>();

        var raw = await context.JournalEntries
            .Where(x => x.Status != EntityStatus.Deleted && x.JournalEntryStatus == status)
            .OrderByDescending(x => x.EntryDate)
            .Select(x => new { x.Id, x.Code, x.EntryDate, x.TotalDebitAmount })
            .Take(30)
            .ToListAsync();

        return raw.Select(x => new ChartDetailItem
        {
            Id       = x.Id,
            Name     = x.Code ?? x.EntryDate.ToString("yyyy/MM/dd"),
            SubLabel = $"NT${x.TotalDebitAmount:N0}"
        }).ToList();
    }
}
