using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace ERPCore2.Models.Enums
{
    /// <summary>
    /// 傳票類型
    /// </summary>
    public enum JournalEntryType
    {
        [Description("自動產生")]
        [Display(Name = "自動產生")]
        AutoGenerated = 1,

        [Description("手動輸入")]
        [Display(Name = "手動輸入")]
        Manual = 2,

        [Description("調整分錄")]
        [Display(Name = "調整分錄")]
        Adjusting = 3,

        [Description("結帳分錄")]
        [Display(Name = "結帳分錄")]
        Closing = 4,

        [Description("沖銷分錄")]
        [Display(Name = "沖銷分錄")]
        Reversing = 5
    }

    /// <summary>
    /// 傳票狀態
    /// </summary>
    public enum JournalEntryStatus
    {
        [Description("草稿")]
        [Display(Name = "草稿")]
        Draft = 1,

        [Description("已過帳")]
        [Display(Name = "已過帳")]
        Posted = 2,

        [Description("已取消")]
        [Display(Name = "已取消")]
        Cancelled = 3,

        [Description("已沖銷")]
        [Display(Name = "已沖銷")]
        Reversed = 4
    }
}
