using ERPCore2.Components.Shared.UI.Form;
using ERPCore2.Data.Entities;
using ERPCore2.Helpers;
using ERPCore2.Models.Enums;
using ERPCore2.Services;

namespace ERPCore2.FieldConfiguration
{
    /// <summary>
    /// 傳票欄位配置
    /// </summary>
    public class JournalEntryFieldConfiguration : BaseFieldConfiguration<JournalEntry>
    {
        private readonly INotificationService? _notificationService;

        public JournalEntryFieldConfiguration(INotificationService? notificationService = null)
        {
            _notificationService = notificationService;
        }

        public override Dictionary<string, FieldDefinition<JournalEntry>> GetFieldDefinitions()
        {
            try
            {
                return new Dictionary<string, FieldDefinition<JournalEntry>>
                {
                    {
                        nameof(JournalEntry.Code),
                        new FieldDefinition<JournalEntry>
                        {
                            PropertyName = nameof(JournalEntry.Code),
                            DisplayName = "傳票號碼",
                            FilterPlaceholder = "輸入傳票號碼搜尋",
                            TableOrder = 1,
                            FilterFunction = (model, query) => FilterHelper.ApplyTextContainsFilter(
                                model, query, nameof(JournalEntry.Code), je => je.Code)
                        }
                    },
                    {
                        nameof(JournalEntry.EntryDate),
                        new FieldDefinition<JournalEntry>
                        {
                            PropertyName = nameof(JournalEntry.EntryDate),
                            DisplayName = "傳票日期",
                            TableOrder = 2,
                            FilterType = SearchFilterType.DateRange,
                            FilterFunction = (model, query) => FilterHelper.ApplyDateRangeFilter(
                                model, query, nameof(JournalEntry.EntryDate), je => je.EntryDate),
                            CustomTemplate = item => builder =>
                            {
                                var entry = (JournalEntry)item;
                                builder.AddContent(0, entry.EntryDate.ToString("yyyy/MM/dd"));
                            }
                        }
                    },
                    {
                        nameof(JournalEntry.EntryType),
                        new FieldDefinition<JournalEntry>
                        {
                            PropertyName = nameof(JournalEntry.EntryType),
                            DisplayName = "傳票類型",
                            TableOrder = 3,
                            FilterType = SearchFilterType.Select,
                            Options = new List<SelectOption>
                            {
                                new SelectOption { Text = "自動產生", Value = ((int)JournalEntryType.AutoGenerated).ToString() },
                                new SelectOption { Text = "手動輸入", Value = ((int)JournalEntryType.Manual).ToString() },
                                new SelectOption { Text = "調整分錄", Value = ((int)JournalEntryType.Adjusting).ToString() },
                                new SelectOption { Text = "結帳分錄", Value = ((int)JournalEntryType.Closing).ToString() },
                                new SelectOption { Text = "沖銷分錄", Value = ((int)JournalEntryType.Reversing).ToString() }
                            },
                            FilterFunction = (model, query) =>
                            {
                                var filterValue = model.GetFilterValue(nameof(JournalEntry.EntryType))?.ToString();
                                if (!string.IsNullOrWhiteSpace(filterValue) &&
                                    int.TryParse(filterValue, out var typeValue) &&
                                    Enum.IsDefined(typeof(JournalEntryType), typeValue))
                                {
                                    var entryType = (JournalEntryType)typeValue;
                                    return query.Where(je => je.EntryType == entryType);
                                }
                                return query;
                            },
                            CustomTemplate = item => builder =>
                            {
                                var entry = (JournalEntry)item;
                                var (text, cssClass) = entry.EntryType switch
                                {
                                    JournalEntryType.AutoGenerated => ("自動", "badge bg-info"),
                                    JournalEntryType.Manual        => ("手動", "badge bg-primary"),
                                    JournalEntryType.Adjusting     => ("調整", "badge bg-warning text-dark"),
                                    JournalEntryType.Closing       => ("結帳", "badge bg-secondary"),
                                    JournalEntryType.Reversing     => ("沖銷", "badge bg-danger"),
                                    _                              => (entry.EntryType.ToString(), "badge bg-secondary")
                                };
                                builder.OpenElement(0, "span");
                                builder.AddAttribute(1, "class", cssClass);
                                builder.AddContent(2, text);
                                builder.CloseElement();
                            }
                        }
                    },
                    {
                        nameof(JournalEntry.JournalEntryStatus),
                        new FieldDefinition<JournalEntry>
                        {
                            PropertyName = nameof(JournalEntry.JournalEntryStatus),
                            DisplayName = "狀態",
                            TableOrder = 4,
                            FilterType = SearchFilterType.Select,
                            Options = new List<SelectOption>
                            {
                                new SelectOption { Text = "草稿", Value = ((int)JournalEntryStatus.Draft).ToString() },
                                new SelectOption { Text = "已過帳", Value = ((int)JournalEntryStatus.Posted).ToString() },
                                new SelectOption { Text = "已取消", Value = ((int)JournalEntryStatus.Cancelled).ToString() },
                                new SelectOption { Text = "已沖銷", Value = ((int)JournalEntryStatus.Reversed).ToString() }
                            },
                            FilterFunction = (model, query) =>
                            {
                                var filterValue = model.GetFilterValue(nameof(JournalEntry.JournalEntryStatus))?.ToString();
                                if (!string.IsNullOrWhiteSpace(filterValue) &&
                                    int.TryParse(filterValue, out var statusValue) &&
                                    Enum.IsDefined(typeof(JournalEntryStatus), statusValue))
                                {
                                    var status = (JournalEntryStatus)statusValue;
                                    return query.Where(je => je.JournalEntryStatus == status);
                                }
                                return query;
                            },
                            CustomTemplate = item => builder =>
                            {
                                var entry = (JournalEntry)item;
                                var (text, cssClass) = entry.JournalEntryStatus switch
                                {
                                    JournalEntryStatus.Draft      => ("草稿", "badge bg-secondary"),
                                    JournalEntryStatus.Posted     => ("已過帳", "badge bg-success"),
                                    JournalEntryStatus.Cancelled  => ("已取消", "badge bg-danger"),
                                    JournalEntryStatus.Reversed   => ("已沖銷", "badge bg-warning text-dark"),
                                    _                             => (entry.JournalEntryStatus.ToString(), "badge bg-secondary")
                                };
                                builder.OpenElement(0, "span");
                                builder.AddAttribute(1, "class", cssClass);
                                builder.AddContent(2, text);
                                builder.CloseElement();
                            }
                        }
                    },
                    {
                        nameof(JournalEntry.Description),
                        new FieldDefinition<JournalEntry>
                        {
                            PropertyName = nameof(JournalEntry.Description),
                            DisplayName = "傳票說明",
                            FilterPlaceholder = "輸入說明搜尋",
                            TableOrder = 5,
                            FilterFunction = (model, query) => FilterHelper.ApplyTextContainsFilter(
                                model, query, nameof(JournalEntry.Description), je => je.Description, allowNull: true),
                            NullDisplayText = "-"
                        }
                    },
                    {
                        nameof(JournalEntry.TotalDebitAmount),
                        new FieldDefinition<JournalEntry>
                        {
                            PropertyName = nameof(JournalEntry.TotalDebitAmount),
                            DisplayName = "借方合計",
                            TableOrder = 6,
                            ShowInFilter = false,
                            CustomTemplate = item => builder =>
                            {
                                var entry = (JournalEntry)item;
                                builder.AddContent(0, entry.TotalDebitAmount.ToString("N2"));
                            }
                        }
                    },
                    {
                        nameof(JournalEntry.TotalCreditAmount),
                        new FieldDefinition<JournalEntry>
                        {
                            PropertyName = nameof(JournalEntry.TotalCreditAmount),
                            DisplayName = "貸方合計",
                            TableOrder = 7,
                            ShowInFilter = false,
                            CustomTemplate = item => builder =>
                            {
                                var entry = (JournalEntry)item;
                                builder.AddContent(0, entry.TotalCreditAmount.ToString("N2"));
                            }
                        }
                    },
                    {
                        nameof(JournalEntry.SourceDocumentCode),
                        new FieldDefinition<JournalEntry>
                        {
                            PropertyName = nameof(JournalEntry.SourceDocumentCode),
                            DisplayName = "來源單號",
                            FilterPlaceholder = "輸入來源單號搜尋",
                            TableOrder = 8,
                            FilterFunction = (model, query) => FilterHelper.ApplyTextContainsFilter(
                                model, query, nameof(JournalEntry.SourceDocumentCode), je => je.SourceDocumentCode, allowNull: true),
                            NullDisplayText = "-"
                        }
                    }
                };
            }
            catch (Exception ex)
            {
                _ = Task.Run(async () =>
                {
                    await ErrorHandlingHelper.HandlePageErrorAsync(
                        ex, nameof(GetFieldDefinitions), GetType(),
                        additionalData: "初始化傳票欄位配置失敗");
                });

                if (_notificationService != null)
                {
                    _ = Task.Run(async () =>
                    {
                        await _notificationService.ShowErrorAsync("初始化傳票欄位配置時發生錯誤，已使用預設配置");
                    });
                }

                return new Dictionary<string, FieldDefinition<JournalEntry>>();
            }
        }
    }
}
