const fs = require('fs');
const path = require('path');

const base = path.join(__dirname, '..', 'Resources');

function escXml(s) {
  return s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
}

function insertKeys(file, keys) {
  let content = fs.readFileSync(file, 'utf8');
  const marker = 'name="Modal.DefaultTitle"';
  const idx = content.indexOf(marker);
  if (idx === -1) { console.log("ERROR: marker not found in " + file); return; }
  const lineStart = content.lastIndexOf('\n', idx) + 1;
  const lines = [];
  for (const [key, val] of Object.entries(keys)) {
    if (content.includes(`name="${key}"`)) continue;
    lines.push(`  <data name="${key}" xml:space="preserve"><value>${escXml(val)}</value></data>`);
  }
  if (lines.length === 0) { console.log("No new keys for " + path.basename(file)); return; }
  const insertion = lines.join('\n') + '\n';
  content = content.slice(0, lineStart) + insertion + content.slice(lineStart);
  fs.writeFileSync(file, content, 'utf8');
  console.log(`Added ${lines.length} keys to ${path.basename(file)}`);
}

// Field.* keys missing from all languages
const fieldKeys = {
  zhTW: {"Field.SubtotalBeforeDiscount":"折扣前小計","Field.QuotationTaxAmount":"報價稅額","Field.DeliveryAddress":"交貨地址","Field.ShippingMethod":"運送方式","Field.ExpectedArrivalDate":"預計到貨日","Field.PurchasePersonnel":"採購人員","Field.PurchaseTaxAmount":"採購稅額","Field.PurchaseTotalAmountIncludingTax":"採購含稅總額","Field.PurchaseReceivingTaxAmount":"進貨稅額","Field.PurchaseReceivingTotalAmountIncludingTax":"進貨含稅總額","Field.ReturnTaxAmount":"退回稅額","Field.TotalReturnAmount":"退回總額","Field.TotalReturnAmountWithTax":"退回含稅總額"},
  enUS: {"Field.SubtotalBeforeDiscount":"Subtotal Before Discount","Field.QuotationTaxAmount":"Quotation Tax","Field.DeliveryAddress":"Delivery Address","Field.ShippingMethod":"Shipping Method","Field.ExpectedArrivalDate":"Expected Arrival Date","Field.PurchasePersonnel":"Purchaser","Field.PurchaseTaxAmount":"Purchase Tax","Field.PurchaseTotalAmountIncludingTax":"Purchase Total (Tax Incl.)","Field.PurchaseReceivingTaxAmount":"Receiving Tax","Field.PurchaseReceivingTotalAmountIncludingTax":"Receiving Total (Tax Incl.)","Field.ReturnTaxAmount":"Return Tax","Field.TotalReturnAmount":"Return Total","Field.TotalReturnAmountWithTax":"Return Total (Tax Incl.)"},
  jaJP: {"Field.SubtotalBeforeDiscount":"割引前小計","Field.QuotationTaxAmount":"見積税額","Field.DeliveryAddress":"配送先住所","Field.ShippingMethod":"配送方法","Field.ExpectedArrivalDate":"入荷予定日","Field.PurchasePersonnel":"購買担当者","Field.PurchaseTaxAmount":"仕入税額","Field.PurchaseTotalAmountIncludingTax":"仕入税込合計","Field.PurchaseReceivingTaxAmount":"入荷税額","Field.PurchaseReceivingTotalAmountIncludingTax":"入荷税込合計","Field.ReturnTaxAmount":"返品税額","Field.TotalReturnAmount":"返品合計","Field.TotalReturnAmountWithTax":"返品税込合計"},
  zhCN: {"Field.SubtotalBeforeDiscount":"折扣前小计","Field.QuotationTaxAmount":"报价税额","Field.DeliveryAddress":"交货地址","Field.ShippingMethod":"运送方式","Field.ExpectedArrivalDate":"预计到货日","Field.PurchasePersonnel":"采购人员","Field.PurchaseTaxAmount":"采购税额","Field.PurchaseTotalAmountIncludingTax":"采购含税总额","Field.PurchaseReceivingTaxAmount":"进货税额","Field.PurchaseReceivingTotalAmountIncludingTax":"进货含税总额","Field.ReturnTaxAmount":"退回税额","Field.TotalReturnAmount":"退回总额","Field.TotalReturnAmountWithTax":"退回含税总额"},
  fil: {"Field.SubtotalBeforeDiscount":"Subtotal Bago Discount","Field.QuotationTaxAmount":"Buwis ng Quotation","Field.DeliveryAddress":"Address ng Delivery","Field.ShippingMethod":"Paraan ng Pagpapadala","Field.ExpectedArrivalDate":"Inaasahang Petsa ng Dating","Field.PurchasePersonnel":"Tauhan ng Pagbili","Field.PurchaseTaxAmount":"Buwis ng Pagbili","Field.PurchaseTotalAmountIncludingTax":"Kabuuang Pagbili (may Buwis)","Field.PurchaseReceivingTaxAmount":"Buwis ng Pagtanggap","Field.PurchaseReceivingTotalAmountIncludingTax":"Kabuuang Pagtanggap (may Buwis)","Field.ReturnTaxAmount":"Buwis ng Pagbalik","Field.TotalReturnAmount":"Kabuuang Pagbalik","Field.TotalReturnAmountWithTax":"Kabuuang Pagbalik (may Buwis)"}
};

// Guide keys - zh-TW (primary)
const guideZhTW = {
"Guide.Quotation.Description":"報價單用於向客戶提供品項報價，包含品名、數量、單價及條件。報價確認後可直接轉為銷貨訂單，避免重複輸入。","Guide.Quotation.TabOverview":"本頁面包含三個分頁：「報價單資料」填寫基本資訊與明細品項；「客戶資訊」查看所選客戶的詳細資料；「報價照片」上傳相關圖片。","Guide.Quotation.Step1":"選擇客戶：搜尋並選擇報價對象","Guide.Quotation.Step2":"填寫基本資料：設定報價日期、稅別、專案名稱等","Guide.Quotation.Step3":"新增報價明細：加入品項、數量與單價","Guide.Quotation.Step4":"確認金額：檢查小計、折扣與稅額是否正確","Guide.Quotation.Step5":"儲存或送審：完成後儲存，或提交審核流程","Guide.Quotation.Field.Code":"系統自動產生，不可手動修改","Guide.Quotation.Field.Customer":"選擇此報價單的客戶，系統會帶入客戶相關資料","Guide.Quotation.Field.Company":"選擇報價所屬公司","Guide.Quotation.Field.Salesperson":"負責此報價的業務員","Guide.Quotation.Field.Date":"報價單建立日期，預設為今天","Guide.Quotation.Field.ProjectName":"關聯的專案名稱，方便後續追蹤","Guide.Quotation.Field.TaxMethod":"選擇計稅方式（含稅、未稅、零稅率）","Guide.Quotation.Field.PaymentTerms":"約定的付款條件","Guide.Quotation.Field.DeliveryTerms":"約定的交貨條件","Guide.Quotation.Field.Remarks":"報價的補充說明，會顯示在列印單據上","Guide.Quotation.Field.Subtotal":"所有品項小計加總（折扣前），系統自動計算","Guide.Quotation.Field.Discount":"品項折扣金額加總，由各品項折扣比例自動計算","Guide.Quotation.Field.TaxAmount":"依據稅別自動計算的稅額","Guide.Quotation.Field.TotalAmount":"報價最終金額 = 小計 - 折扣 + 稅額","Guide.Quotation.Action.ConvertLabel":"轉銷貨訂單","Guide.Quotation.Action.Convert":"將報價單轉為銷貨訂單，系統自動帶入報價明細中尚未轉單的品項","Guide.Quotation.Action.PrintLabel":"列印","Guide.Quotation.Action.Print":"預覽並列印報價單，支援 PDF 與 Excel 匯出","Guide.Quotation.Action.DraftLabel":"儲存草稿","Guide.Quotation.Action.Draft":"暫存未完成的報價單，草稿不進入審核流程","Guide.Quotation.Tip1":"報價單可多次轉單，每次只帶入尚未轉單的剩餘數量。","Guide.Quotation.Tip2":"可設定專案名稱方便日後依專案查詢所有相關報價。","Guide.Quotation.Warning1":"報價單審核通過或已轉單後，基本資料欄位將被鎖定無法修改。","Guide.Quotation.Warning2":"刪除已轉單的明細品項會影響對應訂單的資料，請謹慎操作。","Guide.Quotation.Faq1Q":"報價單可以轉多次訂單嗎？","Guide.Quotation.Faq1A":"可以。每次轉單只會帶入尚未轉單的剩餘數量，直到全部品項都轉完為止。","Guide.Quotation.Faq2Q":"為什麼轉單按鈕無法點擊？","Guide.Quotation.Faq2A":"請確認報價單已儲存、已通過審核（若有啟用審核），且仍有未轉單的品項。","Guide.Quotation.Faq3Q":"如何修改已審核的報價單？","Guide.Quotation.Faq3A":"需先由有權限的人員執行駁回操作，駁回後即可重新編輯。",
"Guide.SalesDelivery.Description":"出貨單記錄實際交付給客戶的品項與數量。通常從銷貨訂單轉入，出貨後可進一步建立退貨單或沖款單。","Guide.SalesDelivery.TabOverview":"本頁面包含兩個分頁：「出貨資料」填寫出貨資訊與明細品項；「客戶資訊」查看客戶的聯絡與地址資料。","Guide.SalesDelivery.Step1":"確認客戶與出貨日期等基本資料","Guide.SalesDelivery.Step2":"從銷貨訂單篩選並帶入出貨品項","Guide.SalesDelivery.Step3":"核對數量與金額是否正確","Guide.SalesDelivery.Step4":"填寫交貨地址與備註","Guide.SalesDelivery.Step5":"儲存出貨單，審核通過後可列印出貨文件","Guide.SalesDelivery.Field.Code":"系統自動產生，格式為 SD + 日期 + 流水號","Guide.SalesDelivery.Field.Customer":"此出貨單的客戶，通常從訂單帶入","Guide.SalesDelivery.Field.Salesperson":"負責此出貨的業務員","Guide.SalesDelivery.Field.DeliveryDate":"實際出貨日期","Guide.SalesDelivery.Field.Address":"客戶收貨地址，可手動修改","Guide.SalesDelivery.Field.TaxMethod":"稅別設定，影響金額計算","Guide.SalesDelivery.Field.Remarks":"出貨的補充說明","Guide.SalesDelivery.Field.TotalAmount":"明細品項小計加總（未含稅）","Guide.SalesDelivery.Field.Discount":"明細折扣金額加總","Guide.SalesDelivery.Field.TaxAmount":"依稅別自動計算的稅額","Guide.SalesDelivery.Field.TotalWithTax":"出貨最終金額 = 總額 + 稅額","Guide.SalesDelivery.Action.ReturnLabel":"轉銷貨退回","Guide.SalesDelivery.Action.Return":"將出貨品項建立退貨單，系統帶入可退貨的品項與數量","Guide.SalesDelivery.Action.SetoffLabel":"轉沖款單","Guide.SalesDelivery.Action.Setoff":"建立沖款單進行收款沖帳作業","Guide.SalesDelivery.Action.PrintLabel":"列印","Guide.SalesDelivery.Action.Print":"預覽並列印出貨單文件","Guide.SalesDelivery.Tip1":"出貨明細會顯示來源訂單資訊，方便追蹤。","Guide.SalesDelivery.Tip2":"可透過篩選條件快速從特定訂單帶入品項。","Guide.SalesDelivery.Warning1":"已建立退貨記錄的出貨品項無法刪除，需先處理退貨單。","Guide.SalesDelivery.Warning2":"出貨單審核通過後欄位將鎖定，如需修改請先駁回。","Guide.SalesDelivery.Faq1Q":"出貨單可以從多張訂單帶入嗎？","Guide.SalesDelivery.Faq1A":"可以。使用篩選條件選擇不同訂單，逐筆帶入品項即可。","Guide.SalesDelivery.Faq2Q":"為什麼無法刪除某些明細？","Guide.SalesDelivery.Faq2A":"已有退貨記錄或沖款記錄的明細不可刪除，請先處理相關單據。","Guide.SalesDelivery.Faq3Q":"如何建立退貨單？","Guide.SalesDelivery.Faq3A":"點擊「轉銷貨退回」按鈕，系統會自動帶入可退貨的品項，填寫退貨數量後儲存即可。",
"Guide.SalesReturn.Description":"銷貨退回單記錄客戶退回的品項與數量，通常從出貨單轉入。退回後可建立沖款單進行退款處理。","Guide.SalesReturn.TabOverview":"本頁面包含兩個分頁：「退回資料」填寫退回資訊與明細品項；「客戶資訊」查看客戶資料。","Guide.SalesReturn.Step1":"確認客戶與退回日期","Guide.SalesReturn.Step2":"選擇退回原因","Guide.SalesReturn.Step3":"從出貨單篩選並帶入退回品項","Guide.SalesReturn.Step4":"填寫退回數量並確認金額","Guide.SalesReturn.Step5":"儲存退回單，審核通過後可進行沖款","Guide.SalesReturn.Field.Code":"系統自動產生，格式為 SR + 日期 + 流水號","Guide.SalesReturn.Field.Customer":"退貨客戶，通常從出貨單帶入","Guide.SalesReturn.Field.ReturnDate":"實際退貨日期","Guide.SalesReturn.Field.Reason":"選擇退貨原因分類","Guide.SalesReturn.Field.TaxMethod":"稅別設定，影響退回金額計算","Guide.SalesReturn.Field.Remarks":"退貨的補充說明","Guide.SalesReturn.Field.TotalReturn":"退回品項小計加總","Guide.SalesReturn.Field.Discount":"退回品項折扣加總","Guide.SalesReturn.Field.TaxAmount":"退回稅額","Guide.SalesReturn.Field.TotalWithTax":"退回含稅總額 = 退回總額 + 稅額","Guide.SalesReturn.Action.SetoffLabel":"轉沖款單","Guide.SalesReturn.Action.Setoff":"建立沖款單進行退款沖帳作業","Guide.SalesReturn.Tip1":"退回明細會自動篩選出可退貨的品項，不需手動核對。","Guide.SalesReturn.Warning1":"已有沖款記錄的退回品項無法修改或刪除。","Guide.SalesReturn.Warning2":"退回數量不可超過原出貨數量減已退數量。","Guide.SalesReturn.Faq1Q":"退回數量有上限嗎？","Guide.SalesReturn.Faq1A":"有。每個品項的退回數量不可超過原出貨數量減去已退貨數量的差額。","Guide.SalesReturn.Faq2Q":"退回後如何退款給客戶？","Guide.SalesReturn.Faq2A":"點擊「轉沖款單」建立沖款單，在沖款單中進行退款沖帳作業。",
"Guide.PurchaseOrder.Description":"採購單用於向廠商下達採購需求，記錄採購品項、數量、單價與交貨條件。審核通過後可轉為進貨單。","Guide.PurchaseOrder.TabOverview":"本頁面包含兩個分頁：「採購單資料」填寫採購資訊與明細品項；「廠商資訊」查看廠商的聯絡與付款資料。","Guide.PurchaseOrder.Step1":"選擇廠商：搜尋並選擇供應廠商","Guide.PurchaseOrder.Step2":"填寫採購資料：設定日期、採購人員、預交日等","Guide.PurchaseOrder.Step3":"新增採購明細：加入品項、數量與單價","Guide.PurchaseOrder.Step4":"確認金額：檢查總金額與稅額是否正確","Guide.PurchaseOrder.Step5":"儲存或送審：完成後儲存，或提交審核流程","Guide.PurchaseOrder.Field.Code":"系統自動產生，格式為 PO + 日期 + 流水號","Guide.PurchaseOrder.Field.Supplier":"選擇採購對象廠商，系統帶入廠商相關資料","Guide.PurchaseOrder.Field.Company":"選擇採購所屬公司","Guide.PurchaseOrder.Field.Personnel":"負責此採購單的採購人員","Guide.PurchaseOrder.Field.OrderDate":"採購單建立日期","Guide.PurchaseOrder.Field.ExpectedDate":"廠商承諾的交貨日期","Guide.PurchaseOrder.Field.TaxMethod":"選擇計稅方式","Guide.PurchaseOrder.Field.Remarks":"採購的補充說明","Guide.PurchaseOrder.Field.TotalAmount":"明細品項小計加總（未含稅）","Guide.PurchaseOrder.Field.TaxAmount":"依稅別自動計算的採購稅額","Guide.PurchaseOrder.Field.TotalWithTax":"採購最終金額 = 總額 + 稅額","Guide.PurchaseOrder.Action.ConvertLabel":"轉進貨單","Guide.PurchaseOrder.Action.Convert":"將採購單轉為進貨單，系統帶入尚未進貨的品項與數量","Guide.PurchaseOrder.Action.CopyMsgLabel":"複製訊息","Guide.PurchaseOrder.Action.CopyMsg":"將採購資訊格式化為文字訊息複製到剪貼簿，方便透過通訊軟體傳送給廠商","Guide.PurchaseOrder.Action.PrintLabel":"列印","Guide.PurchaseOrder.Action.Print":"預覽並列印採購單文件","Guide.PurchaseOrder.Tip1":"「複製訊息」可自訂訊息模板，點擊齒輪圖示即可設定格式。","Guide.PurchaseOrder.Tip2":"預交日預設為採購日後 7 天，可手動調整。","Guide.PurchaseOrder.Warning1":"採購單審核通過後欄位將鎖定，如需修改請先駁回。","Guide.PurchaseOrder.Warning2":"已建立進貨記錄的明細無法刪除，需先處理進貨單。","Guide.PurchaseOrder.Faq1Q":"如何快速向廠商下單？","Guide.PurchaseOrder.Faq1A":"填寫採購單後使用「複製訊息」按鈕，可將訂購資訊複製到通訊軟體直接傳送。","Guide.PurchaseOrder.Faq2Q":"採購單可以轉多次進貨嗎？","Guide.PurchaseOrder.Faq2A":"可以。每次轉單只帶入尚未進貨的剩餘數量，支援分批進貨。","Guide.PurchaseOrder.Faq3Q":"為什麼部分欄位被鎖定？","Guide.PurchaseOrder.Faq3A":"當採購單已審核或已有進貨記錄時，基本資料欄位會鎖定以維持資料一致性。",
"Guide.PurchaseReceiving.Description":"進貨單記錄實際從廠商收到的品項與數量。通常從採購單轉入，可指定入庫倉庫與批號。進貨後可建立退貨單或沖款單。","Guide.PurchaseReceiving.TabOverview":"本頁面包含兩個分頁：「進貨資料」填寫進貨資訊與明細品項；「廠商資訊」查看廠商的聯絡與付款資料。","Guide.PurchaseReceiving.Step1":"選擇廠商：搜尋並選擇供貨廠商","Guide.PurchaseReceiving.Step2":"篩選採購單：從該廠商的採購單中篩選要進貨的單據","Guide.PurchaseReceiving.Step3":"載入明細：使用「智慧載入」或手動帶入採購品項","Guide.PurchaseReceiving.Step4":"確認數量與倉庫：核對進貨數量並指定入庫倉庫","Guide.PurchaseReceiving.Step5":"儲存並審核：完成後儲存，審核通過後品項入庫","Guide.PurchaseReceiving.Field.Code":"系統自動產生，格式為 PR + 日期 + 流水號","Guide.PurchaseReceiving.Field.Supplier":"此進貨單的廠商，通常從採購單帶入","Guide.PurchaseReceiving.Field.ReceiptDate":"實際收到貨品的日期","Guide.PurchaseReceiving.Field.TaxMethod":"稅別設定，影響金額計算方式","Guide.PurchaseReceiving.Field.BatchNumber":"進貨批號，用於追蹤同一批次的品項","Guide.PurchaseReceiving.Field.Remarks":"進貨的補充說明","Guide.PurchaseReceiving.Field.TotalAmount":"明細品項小計加總（未含稅）","Guide.PurchaseReceiving.Field.TaxAmount":"依稅別自動計算的進貨稅額","Guide.PurchaseReceiving.Field.TotalWithTax":"進貨最終金額 = 總額 + 稅額","Guide.PurchaseReceiving.Detail1":"使用「智慧載入」自動帶入採購單中尚未進貨的品項","Guide.PurchaseReceiving.Detail2":"核對每項品目的實際到貨數量，可修改為實際收到數量","Guide.PurchaseReceiving.Detail3":"為每個品項指定入庫倉庫，可使用「統一倉庫」快速設定","Guide.PurchaseReceiving.Detail4":"填寫批號欄位以追蹤品項批次","Guide.PurchaseReceiving.Action.ReturnLabel":"轉採購退回","Guide.PurchaseReceiving.Action.Return":"將進貨品項建立退貨單，系統帶入可退貨的品項與數量","Guide.PurchaseReceiving.Action.SetoffLabel":"轉沖款單","Guide.PurchaseReceiving.Action.Setoff":"建立沖款單進行付款沖帳作業","Guide.PurchaseReceiving.Tip1":"「統一倉庫」功能可一次將所有明細設為相同倉庫，節省逐筆設定。","Guide.PurchaseReceiving.Tip2":"進貨數量可與採購數量不同，系統會追蹤差異以便後續補進。","Guide.PurchaseReceiving.Warning1":"已建立退貨或沖款記錄的明細無法刪除或修改。","Guide.PurchaseReceiving.Faq1Q":"進貨數量可以少於採購數量嗎？","Guide.PurchaseReceiving.Faq1A":"可以。系統會記錄差異，未到貨的品項可在下次進貨時繼續帶入。","Guide.PurchaseReceiving.Faq2Q":"如何處理廠商多送的品項？","Guide.PurchaseReceiving.Faq2A":"可直接在進貨單中手動新增品項或調整數量，不一定要從採購單帶入。",
"Guide.PurchaseReturn.Description":"採購退回單記錄退還給廠商的品項與數量，通常從進貨單轉入。退回後可建立沖款單進行扣款處理。","Guide.PurchaseReturn.TabOverview":"本頁面包含兩個分頁：「退回資料」填寫退回資訊與明細品項；「廠商資訊」查看廠商資料。","Guide.PurchaseReturn.Step1":"確認廠商與退回日期","Guide.PurchaseReturn.Step2":"選擇退回原因","Guide.PurchaseReturn.Step3":"從進貨單篩選並帶入退回品項","Guide.PurchaseReturn.Step4":"填寫退回數量並確認金額","Guide.PurchaseReturn.Step5":"儲存退回單，審核通過後可進行沖款","Guide.PurchaseReturn.Field.Code":"系統自動產生，格式為 PRT + 日期 + 流水號","Guide.PurchaseReturn.Field.Supplier":"退貨廠商，通常從進貨單帶入","Guide.PurchaseReturn.Field.ReturnDate":"實際退貨日期","Guide.PurchaseReturn.Field.Reason":"選擇退貨原因分類","Guide.PurchaseReturn.Field.TaxMethod":"稅別設定，影響退回金額計算","Guide.PurchaseReturn.Field.Remarks":"退貨的補充說明","Guide.PurchaseReturn.Field.TotalReturn":"退回品項小計加總","Guide.PurchaseReturn.Field.TaxAmount":"退回稅額","Guide.PurchaseReturn.Field.TotalWithTax":"退回含稅總額 = 退回總額 + 稅額","Guide.PurchaseReturn.Action.SetoffLabel":"轉沖款單","Guide.PurchaseReturn.Action.Setoff":"建立沖款單進行扣款沖帳作業","Guide.PurchaseReturn.Tip1":"退回明細自動篩選可退品項，依據進貨記錄計算可退數量。","Guide.PurchaseReturn.Warning1":"已有沖款記錄的退回品項無法修改或刪除。","Guide.PurchaseReturn.Warning2":"退回數量不可超過進貨數量減已退數量。","Guide.PurchaseReturn.Faq1Q":"退回數量有上限嗎？","Guide.PurchaseReturn.Faq1A":"有。每個品項的退回數量不可超過原進貨數量減去已退貨數量的差額。","Guide.PurchaseReturn.Faq2Q":"退回後如何向廠商扣款？","Guide.PurchaseReturn.Faq2A":"點擊「轉沖款單」建立沖款單，在沖款單中進行扣款沖帳作業。"
};

// en-US Guide keys (used also as fallback for ja/zh-CN/fil)
const guideEnUS = {
"Guide.Quotation.Description":"Quotations provide item pricing to customers. Once confirmed, they can be converted into sales orders.","Guide.Quotation.TabOverview":"Three tabs: Quotation Data, Customer Info, Photos.","Guide.Quotation.Step1":"Select customer","Guide.Quotation.Step2":"Fill basic info: date, tax type, project name","Guide.Quotation.Step3":"Add line items with quantities and prices","Guide.Quotation.Step4":"Verify subtotals, discounts, and tax","Guide.Quotation.Step5":"Save or submit for approval","Guide.Quotation.Field.Code":"Auto-generated; cannot be manually edited","Guide.Quotation.Field.Customer":"Select the customer for this quotation","Guide.Quotation.Field.Company":"Select the company","Guide.Quotation.Field.Salesperson":"Salesperson for this quotation","Guide.Quotation.Field.Date":"Creation date, defaults to today","Guide.Quotation.Field.ProjectName":"Related project name for tracking","Guide.Quotation.Field.TaxMethod":"Tax calculation method","Guide.Quotation.Field.PaymentTerms":"Agreed payment terms","Guide.Quotation.Field.DeliveryTerms":"Agreed delivery terms","Guide.Quotation.Field.Remarks":"Additional notes for printed documents","Guide.Quotation.Field.Subtotal":"Sum of items before discount; auto-calculated","Guide.Quotation.Field.Discount":"Total discount; auto-calculated","Guide.Quotation.Field.TaxAmount":"Tax based on tax type","Guide.Quotation.Field.TotalAmount":"Final = Subtotal - Discount + Tax","Guide.Quotation.Action.ConvertLabel":"Convert to Sales Order","Guide.Quotation.Action.Convert":"Convert to sales order; auto-populates unconverted items","Guide.Quotation.Action.PrintLabel":"Print","Guide.Quotation.Action.Print":"Preview and print; supports PDF and Excel","Guide.Quotation.Action.DraftLabel":"Save Draft","Guide.Quotation.Action.Draft":"Save as draft; won't enter approval","Guide.Quotation.Tip1":"Can convert multiple times; each brings remaining quantities.","Guide.Quotation.Tip2":"Set project name to search related quotations by project.","Guide.Quotation.Warning1":"Fields locked after approval or conversion.","Guide.Quotation.Warning2":"Deleting converted items may affect related orders.","Guide.Quotation.Faq1Q":"Can convert to orders multiple times?","Guide.Quotation.Faq1A":"Yes, each time brings unconverted remaining quantities.","Guide.Quotation.Faq2Q":"Why is convert button disabled?","Guide.Quotation.Faq2A":"Ensure saved, approved, and has unconverted items.","Guide.Quotation.Faq3Q":"How to edit an approved quotation?","Guide.Quotation.Faq3A":"An authorized user must reject it first.",
"Guide.SalesDelivery.Description":"Delivery notes record items delivered to customers. Usually from sales orders.","Guide.SalesDelivery.TabOverview":"Two tabs: Delivery Data and Customer Info.","Guide.SalesDelivery.Step1":"Confirm customer and delivery date","Guide.SalesDelivery.Step2":"Import items from sales orders","Guide.SalesDelivery.Step3":"Verify quantities and amounts","Guide.SalesDelivery.Step4":"Fill delivery address and remarks","Guide.SalesDelivery.Step5":"Save; print after approval","Guide.SalesDelivery.Field.Code":"Auto-generated: SD + date + sequence","Guide.SalesDelivery.Field.Customer":"Customer, usually from order","Guide.SalesDelivery.Field.Salesperson":"Salesperson for this delivery","Guide.SalesDelivery.Field.DeliveryDate":"Actual delivery date","Guide.SalesDelivery.Field.Address":"Delivery address; editable","Guide.SalesDelivery.Field.TaxMethod":"Tax type for calculation","Guide.SalesDelivery.Field.Remarks":"Additional notes","Guide.SalesDelivery.Field.TotalAmount":"Subtotal (before tax)","Guide.SalesDelivery.Field.Discount":"Total discounts","Guide.SalesDelivery.Field.TaxAmount":"Tax auto-calculated","Guide.SalesDelivery.Field.TotalWithTax":"Final = Total + Tax","Guide.SalesDelivery.Action.ReturnLabel":"Convert to Return","Guide.SalesDelivery.Action.Return":"Create return from delivered items","Guide.SalesDelivery.Action.SetoffLabel":"Convert to Setoff","Guide.SalesDelivery.Action.Setoff":"Create setoff for payment","Guide.SalesDelivery.Action.PrintLabel":"Print","Guide.SalesDelivery.Action.Print":"Preview and print delivery note","Guide.SalesDelivery.Tip1":"Details show source order info for tracking.","Guide.SalesDelivery.Tip2":"Use filters to import from specific orders.","Guide.SalesDelivery.Warning1":"Items with returns cannot be deleted.","Guide.SalesDelivery.Warning2":"Fields locked after approval.","Guide.SalesDelivery.Faq1Q":"Can include items from multiple orders?","Guide.SalesDelivery.Faq1A":"Yes, use filters to select different orders.","Guide.SalesDelivery.Faq2Q":"Why can't I delete some items?","Guide.SalesDelivery.Faq2A":"Items with return/setoff records cannot be deleted.","Guide.SalesDelivery.Faq3Q":"How to create a return?","Guide.SalesDelivery.Faq3A":"Click Convert to Return; system auto-populates returnable items.",
"Guide.SalesReturn.Description":"Sales returns record items returned by customers. Can create setoffs for refunds.","Guide.SalesReturn.TabOverview":"Two tabs: Return Data and Customer Info.","Guide.SalesReturn.Step1":"Confirm customer and return date","Guide.SalesReturn.Step2":"Select return reason","Guide.SalesReturn.Step3":"Import returnable items from deliveries","Guide.SalesReturn.Step4":"Enter return quantities and verify amounts","Guide.SalesReturn.Step5":"Save; create setoff after approval","Guide.SalesReturn.Field.Code":"Auto-generated: SR + date + sequence","Guide.SalesReturn.Field.Customer":"Return customer, from delivery","Guide.SalesReturn.Field.ReturnDate":"Actual return date","Guide.SalesReturn.Field.Reason":"Return reason category","Guide.SalesReturn.Field.TaxMethod":"Tax type for calculation","Guide.SalesReturn.Field.Remarks":"Additional notes","Guide.SalesReturn.Field.TotalReturn":"Return items subtotal","Guide.SalesReturn.Field.Discount":"Return items discount","Guide.SalesReturn.Field.TaxAmount":"Return tax","Guide.SalesReturn.Field.TotalWithTax":"Return total with tax","Guide.SalesReturn.Action.SetoffLabel":"Convert to Setoff","Guide.SalesReturn.Action.Setoff":"Create setoff for refund","Guide.SalesReturn.Tip1":"Auto-filters returnable items.","Guide.SalesReturn.Warning1":"Items with setoff records cannot be modified.","Guide.SalesReturn.Warning2":"Return qty cannot exceed delivered minus returned.","Guide.SalesReturn.Faq1Q":"Return qty limit?","Guide.SalesReturn.Faq1A":"Cannot exceed delivered minus already returned.","Guide.SalesReturn.Faq2Q":"How to refund?","Guide.SalesReturn.Faq2A":"Click Convert to Setoff.",
"Guide.PurchaseOrder.Description":"Purchase orders record procurement requests to suppliers. Convert to receiving after approval.","Guide.PurchaseOrder.TabOverview":"Two tabs: PO Data and Supplier Info.","Guide.PurchaseOrder.Step1":"Select supplier","Guide.PurchaseOrder.Step2":"Fill order details: dates, purchaser","Guide.PurchaseOrder.Step3":"Add line items","Guide.PurchaseOrder.Step4":"Verify amounts and tax","Guide.PurchaseOrder.Step5":"Save or submit for approval","Guide.PurchaseOrder.Field.Code":"Auto-generated: PO + date + sequence","Guide.PurchaseOrder.Field.Supplier":"Select supplier; auto-fills info","Guide.PurchaseOrder.Field.Company":"Select purchasing company","Guide.PurchaseOrder.Field.Personnel":"Purchaser for this PO","Guide.PurchaseOrder.Field.OrderDate":"PO creation date","Guide.PurchaseOrder.Field.ExpectedDate":"Supplier's promised delivery date","Guide.PurchaseOrder.Field.TaxMethod":"Tax calculation method","Guide.PurchaseOrder.Field.Remarks":"Additional notes","Guide.PurchaseOrder.Field.TotalAmount":"Subtotal (before tax)","Guide.PurchaseOrder.Field.TaxAmount":"Purchase tax","Guide.PurchaseOrder.Field.TotalWithTax":"Final = Total + Tax","Guide.PurchaseOrder.Action.ConvertLabel":"Convert to Receiving","Guide.PurchaseOrder.Action.Convert":"Convert to receiving; auto-populates unreceived items","Guide.PurchaseOrder.Action.CopyMsgLabel":"Copy Message","Guide.PurchaseOrder.Action.CopyMsg":"Format order as text for messaging to supplier","Guide.PurchaseOrder.Action.PrintLabel":"Print","Guide.PurchaseOrder.Action.Print":"Preview and print PO","Guide.PurchaseOrder.Tip1":"Copy Message supports custom templates via gear icon.","Guide.PurchaseOrder.Tip2":"Expected date defaults to 7 days after order date.","Guide.PurchaseOrder.Warning1":"Fields locked after approval.","Guide.PurchaseOrder.Warning2":"Items with receiving records cannot be deleted.","Guide.PurchaseOrder.Faq1Q":"How to quickly order from supplier?","Guide.PurchaseOrder.Faq1A":"Use Copy Message to send via messaging app.","Guide.PurchaseOrder.Faq2Q":"Can receive in multiple batches?","Guide.PurchaseOrder.Faq2A":"Yes, each conversion brings unreceived quantities.","Guide.PurchaseOrder.Faq3Q":"Why are fields locked?","Guide.PurchaseOrder.Faq3A":"Fields lock when approved or has receiving records.",
"Guide.PurchaseReceiving.Description":"Receiving notes record items received from suppliers. Can specify warehouses and batch numbers.","Guide.PurchaseReceiving.TabOverview":"Two tabs: Receiving Data and Supplier Info.","Guide.PurchaseReceiving.Step1":"Select supplier","Guide.PurchaseReceiving.Step2":"Filter PO to receive from","Guide.PurchaseReceiving.Step3":"Use Smart Load to import items","Guide.PurchaseReceiving.Step4":"Verify quantities and assign warehouses","Guide.PurchaseReceiving.Step5":"Save and approve; items stocked on approval","Guide.PurchaseReceiving.Field.Code":"Auto-generated: PR + date + sequence","Guide.PurchaseReceiving.Field.Supplier":"Supplier, usually from PO","Guide.PurchaseReceiving.Field.ReceiptDate":"Actual date goods received","Guide.PurchaseReceiving.Field.TaxMethod":"Tax type for calculation","Guide.PurchaseReceiving.Field.BatchNumber":"Batch number for tracking","Guide.PurchaseReceiving.Field.Remarks":"Additional notes","Guide.PurchaseReceiving.Field.TotalAmount":"Subtotal (before tax)","Guide.PurchaseReceiving.Field.TaxAmount":"Receiving tax","Guide.PurchaseReceiving.Field.TotalWithTax":"Final = Total + Tax","Guide.PurchaseReceiving.Detail1":"Smart Load imports unreceived PO items","Guide.PurchaseReceiving.Detail2":"Verify actual received qty per item","Guide.PurchaseReceiving.Detail3":"Assign warehouses; use Unify Warehouse for batch setting","Guide.PurchaseReceiving.Detail4":"Fill batch number for tracking","Guide.PurchaseReceiving.Action.ReturnLabel":"Convert to Return","Guide.PurchaseReceiving.Action.Return":"Create return from received items","Guide.PurchaseReceiving.Action.SetoffLabel":"Convert to Setoff","Guide.PurchaseReceiving.Action.Setoff":"Create setoff for payment","Guide.PurchaseReceiving.Tip1":"Unify Warehouse sets all items to same warehouse.","Guide.PurchaseReceiving.Tip2":"Received qty can differ from ordered; system tracks difference.","Guide.PurchaseReceiving.Warning1":"Items with returns/setoffs cannot be deleted.","Guide.PurchaseReceiving.Faq1Q":"Can receive less than ordered?","Guide.PurchaseReceiving.Faq1A":"Yes, remaining can be imported next time.","Guide.PurchaseReceiving.Faq2Q":"How to handle extra items?","Guide.PurchaseReceiving.Faq2A":"Manually add items; not required from PO.",
"Guide.PurchaseReturn.Description":"Purchase returns record items returned to suppliers. Can create setoffs for deductions.","Guide.PurchaseReturn.TabOverview":"Two tabs: Return Data and Supplier Info.","Guide.PurchaseReturn.Step1":"Confirm supplier and return date","Guide.PurchaseReturn.Step2":"Select return reason","Guide.PurchaseReturn.Step3":"Import returnable items from receiving","Guide.PurchaseReturn.Step4":"Enter return quantities and verify amounts","Guide.PurchaseReturn.Step5":"Save; create setoff after approval","Guide.PurchaseReturn.Field.Code":"Auto-generated: PRT + date + sequence","Guide.PurchaseReturn.Field.Supplier":"Return supplier, from receiving","Guide.PurchaseReturn.Field.ReturnDate":"Actual return date","Guide.PurchaseReturn.Field.Reason":"Return reason category","Guide.PurchaseReturn.Field.TaxMethod":"Tax type for calculation","Guide.PurchaseReturn.Field.Remarks":"Additional notes","Guide.PurchaseReturn.Field.TotalReturn":"Return subtotal","Guide.PurchaseReturn.Field.TaxAmount":"Return tax","Guide.PurchaseReturn.Field.TotalWithTax":"Return total with tax","Guide.PurchaseReturn.Action.SetoffLabel":"Convert to Setoff","Guide.PurchaseReturn.Action.Setoff":"Create setoff for deduction","Guide.PurchaseReturn.Tip1":"Auto-filters returnable items from receiving.","Guide.PurchaseReturn.Warning1":"Items with setoff records cannot be modified.","Guide.PurchaseReturn.Warning2":"Return qty cannot exceed received minus returned.","Guide.PurchaseReturn.Faq1Q":"Return qty limit?","Guide.PurchaseReturn.Faq1A":"Cannot exceed received minus already returned.","Guide.PurchaseReturn.Faq2Q":"How to deduct from supplier?","Guide.PurchaseReturn.Faq2A":"Click Convert to Setoff."
};

// Insert zh-TW
insertKeys(path.join(base, "SharedResource.resx"), {...fieldKeys.zhTW, ...guideZhTW});
// Insert en-US
insertKeys(path.join(base, "SharedResource.en-US.resx"), {...fieldKeys.enUS, ...guideEnUS});
// ja-JP, zh-CN, fil: field keys in native + guide keys from en-US
insertKeys(path.join(base, "SharedResource.ja-JP.resx"), {...fieldKeys.jaJP, ...guideEnUS});
insertKeys(path.join(base, "SharedResource.zh-CN.resx"), {...fieldKeys.zhCN, ...guideEnUS});
insertKeys(path.join(base, "SharedResource.fil.resx"), {...fieldKeys.fil, ...guideEnUS});

console.log("Done!");
